-- =============================================================================
-- ROLE-BASED ACCESS CONTROL (RBAC)
-- Adventure Works Capstone Project
-- Purpose : Define roles, grant privileges, and set up least-privilege access
--           across BRONZE, SILVER, and GOLD layers.
-- =============================================================================

-- =============================================================================
-- 1. CREATE CUSTOM ROLES
-- =============================================================================

-- Hierarchy (top to bottom — each role inherits from role above):
-- SYSADMIN
--   └─ CAPSTONE_SYSADMIN
--        ├─ CAPSTONE_DATA_ENGINEER  (full ETL access to all layers)
--        ├─ CAPSTONE_ANALYST        (read-only on GOLD + views)
--        └─ CAPSTONE_VIEWER         (read-only on GOLD views only)

CREATE ROLE IF NOT EXISTS CAPSTONE_SYSADMIN
    COMMENT = 'Top-level admin for the capstone project';

CREATE ROLE IF NOT EXISTS CAPSTONE_DATA_ENGINEER
    COMMENT = 'ETL engineers — full read/write on BRONZE and SILVER; read on GOLD';

CREATE ROLE IF NOT EXISTS CAPSTONE_ANALYST
    COMMENT = 'Data analysts — read-only on GOLD tables and views';

CREATE ROLE IF NOT EXISTS CAPSTONE_VIEWER
    COMMENT = 'Business users — read-only on analytical views in GOLD only';

-- Role hierarchy
GRANT ROLE CAPSTONE_DATA_ENGINEER TO ROLE CAPSTONE_SYSADMIN;
GRANT ROLE CAPSTONE_ANALYST        TO ROLE CAPSTONE_SYSADMIN;
GRANT ROLE CAPSTONE_VIEWER         TO ROLE CAPSTONE_ANALYST;

-- Grant CAPSTONE_SYSADMIN to SYSADMIN (platform admin)
GRANT ROLE CAPSTONE_SYSADMIN TO ROLE SYSADMIN;

-- =============================================================================
-- 2. WAREHOUSE GRANTS
-- =============================================================================

GRANT USAGE ON WAREHOUSE COMPUTE_WH          TO ROLE CAPSTONE_SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH          TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE CAPSTONE_ANALYTICS_WH TO ROLE CAPSTONE_ANALYST;
GRANT USAGE ON WAREHOUSE CAPSTONE_ANALYTICS_WH TO ROLE CAPSTONE_VIEWER;

-- =============================================================================
-- 3. DATABASE GRANTS
-- =============================================================================

GRANT USAGE ON DATABASE ADVENTURE_WORKS_DB TO ROLE CAPSTONE_SYSADMIN;
GRANT USAGE ON DATABASE ADVENTURE_WORKS_DB TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT USAGE ON DATABASE ADVENTURE_WORKS_DB TO ROLE CAPSTONE_ANALYST;
GRANT USAGE ON DATABASE ADVENTURE_WORKS_DB TO ROLE CAPSTONE_VIEWER;

-- =============================================================================
-- 4. SCHEMA GRANTS
-- =============================================================================

-- BRONZE schema — Data Engineers full access; no access for Analysts/Viewers
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA ADVENTURE_WORKS_DB.BRONZE TO ROLE CAPSTONE_SYSADMIN;
GRANT USAGE, CREATE TABLE, CREATE STAGE
    ON SCHEMA ADVENTURE_WORKS_DB.BRONZE TO ROLE CAPSTONE_DATA_ENGINEER;

-- SILVER schema — Data Engineers full access; read for Analysts
GRANT USAGE, CREATE TABLE
    ON SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_SYSADMIN;
GRANT USAGE, CREATE TABLE
    ON SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT USAGE
    ON SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_ANALYST;

-- GOLD schema — Data Engineers read/write; Analysts read; Viewers view only
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW
    ON SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_SYSADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT USAGE
    ON SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_ANALYST;
GRANT USAGE
    ON SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_VIEWER;

-- =============================================================================
-- 5. TABLE-LEVEL GRANTS
-- =============================================================================

-- BRONZE — Data Engineer full DML
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA ADVENTURE_WORKS_DB.BRONZE TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA ADVENTURE_WORKS_DB.BRONZE TO ROLE CAPSTONE_DATA_ENGINEER;

-- SILVER — Data Engineer full DML; Analyst read
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT SELECT
    ON ALL TABLES IN SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_ANALYST;
GRANT SELECT
    ON FUTURE TABLES IN SCHEMA ADVENTURE_WORKS_DB.SILVER TO ROLE CAPSTONE_ANALYST;

-- GOLD — Data Engineer write; Analyst & Viewer read
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_DATA_ENGINEER;
GRANT SELECT
    ON ALL TABLES IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_ANALYST;
GRANT SELECT
    ON FUTURE TABLES IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_ANALYST;

-- GOLD views — Analyst + Viewer read
GRANT SELECT
    ON ALL VIEWS IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_ANALYST;
GRANT SELECT
    ON FUTURE VIEWS IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_ANALYST;
GRANT SELECT
    ON ALL VIEWS IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_VIEWER;
GRANT SELECT
    ON FUTURE VIEWS IN SCHEMA ADVENTURE_WORKS_DB.GOLD TO ROLE CAPSTONE_VIEWER;

-- =============================================================================
-- 6. CREATE SAMPLE USERS AND ASSIGN ROLES
-- (Change passwords before using in production)
-- =============================================================================

CREATE USER IF NOT EXISTS ETL_SERVICE_USER
    PASSWORD            = 'Change_Me_2024!'
    DEFAULT_ROLE        = CAPSTONE_DATA_ENGINEER
    DEFAULT_WAREHOUSE   = COMPUTE_WH
    DEFAULT_NAMESPACE   = ADVENTURE_WORKS_DB.BRONZE
    MUST_CHANGE_PASSWORD = TRUE
    COMMENT             = 'Service account for ETL pipelines';

CREATE USER IF NOT EXISTS ANALYST_USER
    PASSWORD            = 'Change_Me_2024!'
    DEFAULT_ROLE        = CAPSTONE_ANALYST
    DEFAULT_WAREHOUSE   = CAPSTONE_ANALYTICS_WH
    DEFAULT_NAMESPACE   = ADVENTURE_WORKS_DB.GOLD
    MUST_CHANGE_PASSWORD = TRUE
    COMMENT             = 'Sample analyst user — read-only on GOLD';

CREATE USER IF NOT EXISTS VIEWER_USER
    PASSWORD            = 'Change_Me_2024!'
    DEFAULT_ROLE        = CAPSTONE_VIEWER
    DEFAULT_WAREHOUSE   = CAPSTONE_ANALYTICS_WH
    DEFAULT_NAMESPACE   = ADVENTURE_WORKS_DB.GOLD
    MUST_CHANGE_PASSWORD = TRUE
    COMMENT             = 'Business user — views only';

GRANT ROLE CAPSTONE_DATA_ENGINEER TO USER ETL_SERVICE_USER;
GRANT ROLE CAPSTONE_ANALYST        TO USER ANALYST_USER;
GRANT ROLE CAPSTONE_VIEWER         TO USER VIEWER_USER;

-- =============================================================================
-- 7. VERIFY ROLE ASSIGNMENTS
-- =============================================================================
SHOW GRANTS TO ROLE CAPSTONE_DATA_ENGINEER;
SHOW GRANTS TO ROLE CAPSTONE_ANALYST;
SHOW GRANTS TO ROLE CAPSTONE_VIEWER;
SHOW GRANTS ON DATABASE ADVENTURE_WORKS_DB;
SHOW GRANTS ON SCHEMA ADVENTURE_WORKS_DB.GOLD;
