name: Snowflake Capstone CI

on:
  push:
    branches: [ main, develop, "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install security tools
        run: pip install bandit detect-secrets

      - name: Run Bandit security scan
        continue-on-error: true
        run: bandit -r config/ bronze_scripts/ silver_scripts/ gold_scripts/ exports/ -ll -ii -f txt

      - name: Check for hardcoded secrets
        continue-on-error: true
        run: detect-secrets scan > secrets_report.json && cat secrets_report.json
